version: '3'

services:
  web_ghost:
    image: ghost:3-alpine
    restart: always
    ports:
      - 81:2368
    environment:
      database__client: mysql
      database__connection__host: database
      database__connection__user: root
      database__connection__password: P@ssw0rd123!!
      database__connection__database: db_ghost
      url: http://localhost:81
    volumes: 
      - ./data:/var/lib/ghost/content
    networks: 
      - ghost_network

  database:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: P@ssw0rd123!!
      MYSQL_DATABASE: db_ghost
    volumes: 
      - ./mysql:/var/lib/mysql
    networks: 
      - ghost_network

networks: 
  ghost_network: